name: paddle
channels:
  - defaults
dependencies:
  - python=3.11.14
  - pip=26.0.1
  - pip:
      - paddlepaddle==3.0.0
      - paddleocr==2.8.1
      - opencv-python==4.6.0.66
      - pillow==12.1.1
      - numpy==1.26.4
      - PyQt5==5.15.11
      - pyyaml==6.0.2
      - requests==2.32.5
      - tqdm==4.67.3
      - shapely==2.1.2
      - pyclipper==1.4.0
      - scikit-image==0.26.0
      - matplotlib==3.10.8